/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Placeholder stub so the library builds. Real components land in Phases 03–05.
     */
    interface RfStub {
    }
}
declare global {
    /**
     * Placeholder stub so the library builds. Real components land in Phases 03–05.
     */
    interface HTMLRfStubElement extends Components.RfStub, HTMLStencilElement {
    }
    var HTMLRfStubElement: {
        prototype: HTMLRfStubElement;
        new (): HTMLRfStubElement;
    };
    interface HTMLElementTagNameMap {
        "rf-stub": HTMLRfStubElement;
    }
}
declare namespace LocalJSX {
    /**
     * Placeholder stub so the library builds. Real components land in Phases 03–05.
     */
    interface RfStub {
    }
    interface IntrinsicElements {
        "rf-stub": RfStub;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Placeholder stub so the library builds. Real components land in Phases 03–05.
             */
            "rf-stub": LocalJSX.IntrinsicElements["rf-stub"] & JSXBase.HTMLAttributes<HTMLRfStubElement>;
        }
    }
}
